check/urls.py
from django.urls import path
from .views import checking_serial
# create urls here


app_name = 'check'





urlpatterns = [
    path('', checking_serial, name='check_serial'),


]

contact/urls.py
from django.urls import path
from .views import contact
# create urls here


app_name = 'contact'





urlpatterns = [
    path('', contact, name='contact'),


]

pharmarose/urls.py
"""pharmarose URL Configuration"""


from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import home, about




urlpatterns = [
    path('eslam-admin/', admin.site.urls),
    path('', home, name='home'),
    path('about-us/', about, name='about'),
    path('products/', include('products.urls', namespace='products')),
    path('check-code/', include('check.urls', namespace='check')),
    path('contact-us/', include('contact.urls', namespace='contact')),


]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

products/urls.py
from django.urls import path
from .views import category_product_list, ProductListView, ProductDetailView, SearchProduct
# create urls here


app_name = 'products'





urlpatterns = [
    path('', ProductListView.as_view(), name='product_list'),
    path('results/', SearchProduct.as_view(), name='search_results'),
    path('<slug:slug>/', category_product_list, name='category_product_list'),
    path('single-product/<slug:slug>/', ProductDetailView.as_view(), name='product_detail'),
]

check/models.py
from django.db import models
from django.dispatch import receiver
from django.db.models.signals import post_save
from products.models import Product
from .utils import generate_key

class Checking(models.Model):
    product = models.ForeignKey(
        Product, 
        on_delete=models.CASCADE, 
        related_name="products", 
        blank=True, null=True
    )
    bar_code        = models.CharField(max_length=50, unique=True)
    serial_number   = models.CharField(max_length=50, unique=True)

    def __str__(self):
        return str(self.serial_number)


@receiver(post_save, sender=Product)
def create_checking_for_product(sender, instance, *args, **kwargs):
    check = Checking.objects.filter(product=instance)
    difference = abs(check.count() - instance.quantity)
    if instance and instance.quantity and difference > 0:
        for _ in range(difference):
            Checking.objects.create(
                product=instance, 
                bar_code=generate_key(5), 
                serial_number=generate_key(7)
            )

contact/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models
from django.db.models.signals import pre_save
from django.dispatch import receiver
from .utils import unique_slug_generator
# Create your models here.

class Category(models.Model):
    name = models.CharField(max_length=100)
    slug = models.SlugField(blank=True)
    parent = models.ForeignKey(
        'self', 
        on_delete=models.CASCADE, 
        related_name="children", 
        blank=True, null=True
    )


    def __str__(self):
        return self.name

        

class Product(models.Model):
    name = models.CharField(max_length=100, unique=True)
    slug = models.SlugField(blank=True)
    text = models.TextField(blank=True)
    image = models.ImageField(upload_to="products", blank=True)
    category = models.ForeignKey(
        Category, 
        related_name='categories', 
        on_delete=models.CASCADE, 
        blank=True, null=True
    )
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return self.name

    # def get_absolute_url(self):
    #     return reverse("products:detail", kwargs={"slug":self.slug})



# Slug signals
@receiver(pre_save, sender=Product)
def product_slug_automaticaly(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)


@receiver(pre_save, sender=Category)
def category_slug_automaticaly(sender, instance, *args, **kwargs):
    if not instance.slug:
        instance.slug = unique_slug_generator(instance)

contact/forms.py
from django import forms

# contact forms


class ContactForm(forms.Form):
    name        = forms.CharField(required=False, max_length=100, widget=forms.TextInput(attrs={'placeholder':'your full name'}))
    email       = forms.EmailField(required=True, widget=forms.TextInput(attrs={'placeholder':'example@gmail.com'}))
    message     = forms.CharField(required=True,widget=forms.Textarea)

check/views.py
from django.shortcuts import render
from .models import Checking
from django.db.models import Q
# Create your views here.


def checking_serial(request):
    qs = Checking.objects.all()

    barcode = request.GET.get('code')
    serial = request.GET.get('serial')

    if serial != '' and serial is not None and barcode != '' and barcode is not None:
        qs = qs.filter(Q(serial_number__iexact=serial) & Q(bar_code__iexact=barcode))

    context = {
        "queryset":qs,
        "barcode":barcode,
        "serial":serial
    }


    return render(request , "check/check_code.html", context)

contact/views.py
from django.shortcuts import render, redirect
from django.core.mail import send_mail
from .forms import ContactForm
from django.conf import settings
from django.contrib import messages
# Create your views here.


def contact(request):
    title = 'Contact-US'
    form = ContactForm()
    if request.method == 'POST':
        form = ContactForm(request.POST)

        if form.is_valid():
            name = form.cleaned_data['name']
            emailFrom = form.cleaned_data['email']
            message = form.cleaned_data['message']
            subject = 'message from {n}'.format(n=name)
            emailTo = settings.EMAIL_HOST_USER
            # emailTo = getattr(settings, "EMAIL_HOST_USER", "thomas.adel31@gmail.com")
            send_mail(subject, message, emailFrom, [emailTo], fail_silently=True)

            messages.success(request, "Your Message Has Been Sent, Our staff will call back later and answer your questions.")
            return redirect("contact:contact")
    else:
        form = ContactForm()



    context = {
        'form': form,
        'title': title
    }

    return render(request, 'contact/contact.html', context)






#
# send_mail(
#     'Subject here',
#     'Here is the message.',
#     'from@example.com',
#     ['to@example.com'],
#     fail_silently=False,
# )

pharmarose/views.py
from django.shortcuts import render


# main Views


def home(request):
    return render(request, 'home2.html', {})


def about(request):
    return render(request, 'about.html', {})

products/views.py
from django.shortcuts import render, get_object_or_404
from .models import Category, Product
from django.views.generic import ListView, DetailView
from django.core.paginator import Paginator
# Create your views here.


class SearchProduct(ListView):
    model = Product
    template_name = 'products/search.html'

    def get_queryset(self):
        query = self.request.GET.get("search")
        object_list = Product.objects.filter(name__icontains=query)
        return object_list

class ProductListView(ListView):
    model = Product
    template_name = 'products/product_list.html'
    paginate_by = 10



class ProductDetailView(DetailView):
    model = Product
    template_name = 'products/product_detail.html'



def category_product_list(request, slug):
    categories = Category.objects.all()
    product = Product.objects.all()

    category = get_object_or_404(Category, slug=slug)
    products = product.filter(category=category)

    # Pagination
    paginator = Paginator(products, 10)
    page = request.GET.get('page')
    product_page = paginator.get_page(page)


    context = {
        'category': category,
        'all_product': product,
        'categories': categories,
        'products': products,
        'product_page': product_page
        }

    return render(request,'category/categoties.html',context)

products/templates/category/categoties.html
{% extends "base.html" %}

{% block title %}Products | {{category.name}}{% endblock %}

{% block content %}
<!-- Breadcrumb Area Start -->
<section class="breadcrumb-area section-padding-80">
    <div class="container">
        <div class="row">
            <div class="col-12">
                <div class="breadcrumb-content">
                    <h2 style="margin-bottom: 20px; margin-top: 50px;">{{category.name}}</h2>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Area End -->

<section class="product spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 col-md-7">
                <div class="product__discount">
                    <div class="section-title product__discount__title">
                        <h2>Products</h2>
                    </div>
                    <div class="row">
                      {% for product in products %}
                        <div class="col-lg-4">
                            <div class="product__discount__item">
                              {% if product.image %}
                              <a href="{% url 'products:product_detail' product.slug %}">
                                  <div class="product__discount__item__pic set-bg"
                                      data-setbg="{{product.image.url}}">
                                  </div>
                                </a>
                              {% endif %}

                                <div class="product__discount__item__text">
                                    {% if product.category %}
                                      <span>{{product.category}}</span>
                                    {% else %}
                                      <span>No Category Related</span>
                                    {% endif %}
                                    <h5><a href="{% url 'products:product_detail' product.slug %}">{{product.name}}</a></h5>
                                    <div class="product__item__price">
                                    {{product.text|truncatewords:6}}...etc
                                    <a href="{% url 'products:product_detail' product.slug %}" 
                                    class="btn btn-warning btn-sm" style="height: 28px; background: #7ead39;">More</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                      {% empty %}
                      <div class="post-content text-center">
                        <p>Sorry, No there any Products Yet!</p>
                      </div>
                    {% endfor %}
                    </div>
                </div>
            </div>
</section>
<section>
  {% if product_page.has_next %}
      <div class="row">
        <div class="col-12 text-center">
          <a href="?page={{ product_page.next_page_number }}" class="btn akame-btn active mt-30">Load More</a>
        </div>
      </div>
  {% endif %}
</section>
<!-- News Area End -->
{% endblock %}

products/templates/products/product_detail.html
{% extends "base.html" %}

{% block title %}Ferrun Pharma | {{object.name}}{% endblock %}

{% block content %}

<section class="product-details spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-6 col-md-6">
                <div class="product__details__pic">
                    <div class="product__details__pic__item">
                    {% if object.image %}
                        <img class="product__details__pic__item--large"
                            src="{{object.image.url}}" alt="" height="400px" width="200px">
                    {% endif %}
                        
                    </div>
                </div>
            </div>
            <div class="col-lg-6 col-md-6">
                <div class="product__details__text">
                    <h3>{{object.name}}</h3>
                    <p>{{object.text}}</p>
                </div>
            </div>
            
        </div>
    </div>
</section>


<!-- Blog Details Area Start 
<section class="akame-blog-details-area section-padding-80">
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-12 col-lg-10">
                <div class="post-content">
                    <h2 class="post-title">{{object.name}}</h2>
                </div>
            </div>
        </div>

        <div class="row">
            <div class="col-12">
              {% if object.image %}
                <div class="post-thumbnail mb-50">
                    <img src="{{object.image.url}}" height="400px" width="400px" alt="">
                </div>
              {% endif %}
            </div>
        </div>

        <div class="row justify-content-center">

            <div class="col-10 col-md-10 col-lg-9">
                <div class="blog-details-text">
                    <p>{{object.text}}</p>
                </div>
            </div>
</section>
-->

{% endblock %}

products/templates/products/product_list.html
{% extends "base.html" %}

{% block title %}Ferrun Pharma | Products{% endblock %}

{% block content %}

<section class="product spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-9 col-md-7">
                <div class="product__discount">
                    <div class="section-title product__discount__title">
                        <h2>Products</h2>
                    </div>
                    <div class="row">
                      {% for product in object_list %}
                        <div class="col-lg-4">
                            <div class="product__discount__item">
                              {% if product.image %}
                              <a href="{% url 'products:product_detail' product.slug %}">
                                  <div class="product__discount__item__pic set-bg"
                                      data-setbg="{{product.image.url}}">
                                  </div>
                                </a>
                              {% endif %}

                                <div class="product__discount__item__text">
                                    {% if product.category %}
                                      <span>{{product.category}}</span>
                                    {% else %}
                                      <span>No Category Related</span>
                                    {% endif %}
                                    <h5><a href="{% url 'products:product_detail' product.slug %}">{{product.name}}</a></h5>
                                    <div class="product__item__price">
                                    {{product.text|truncatewords:6}}...etc
                                    <a href="{% url 'products:product_detail' product.slug %}" 
                                    class="btn btn-warning btn-sm" style="height: 28px; background: #7ead39;">More</a>
                                    </div>
                                </div>
                            </div>
                        </div>
                      {% empty %}
                      <div class="post-content text-center">
                        <p>Sorry, No there any Products Yet!</p>
                      </div>
                    {% endfor %}
                    </div>
                </div>
            </div>
</section>

<!-- 
<section class="akame-news-area my-5 section-padding-0-80">
    <div class="container">

      <div class="row">
        {% for category in all_categories %}
          <div class="col-sm-2 my-2">
              <a style="font-weight: bold;" class="btn akame-btn" href="{% url 'products:category_product_list' category.slug %}">
                {{category.name}}
              </a>
          </div>
        {% endfor %}
      </div>
    <div class="row my-5 mx-sm-n4 akame-blog-masonary">
          {% for product in object_list %}
            <div class="col-12 col-sm-6 col-lg-4 px-4 akame-blog-masonary-item mb-50 wow fadeInUp" data-wow-delay="200ms">
                <div class="single-post-area">
                  {% if product.image %}
                    <div class="post-thumbnail">
                        <img style="height: 200px; width: 200px;" src="{{product.image.url}}" >
                    </div>
                  {% endif %}
                    <div class="post-content">
                        <a style='text-decoration:none;' href="{% url 'products:product_detail' product.slug %}" class="post-title">{{product.name}}</a>
                        <p>
                          {{product.text|truncatewords:6}}
                          <a href="{% url 'products:product_detail' product.slug %}" class="btn btn-warning btn-sm" style="background: #ed790b;">Read More</a>
                        </p>
                    </div>
                </div>
            </div>
          {% empty %}
            <div class="post-content text-center">
              <p>Sorry, No there any Products Yet!</p>
            </div>
          {% endfor %}
        </div> 
      </div>
</section>
News Area End -->

<section>
  {% if is_paginated %}
      {% if page_obj.has_next %}
          <div class="row">
            <div class="col-12 text-center">
              <a href="?page={{ page_obj.next_page_number }}" class="btn akame-btn active mt-30">Load More</a>
            </div>
          </div>
      {% endif %}
  {% endif %}
</section>



{% endblock %}

templates/base/footer.html
{% load static %}

<!-- <hr>
<footer class="footer-area section-padding-80-0">
    <div class="container">
        <div class="row justify-content-between">

            <div class="col-12 col-sm-6 col-md-4">
                <div class="single-footer-widget mb-80">

                    <a style='text-decoration:none;' class="widget-title" href="{% url 'home' %}" class="footer-logo">
                      <img src="{% static 'img/rose.png' %}" width="25" height="25"> Pharma Rose
                    </a>

                    <p class="mb-30">The House of Bodybuilding Products</p>

                    <div class="copywrite-text">
                        <p>
                          Copyright &copy; {% now "Y" %} All rights reserved
                        </p>
                    </div>
                </div>
            </div>

            <div class="col-12 col-sm-6 col-md-4 col-xl-3">
                <div class="single-footer-widget mb-80">

                    <div class="social-info">
                        <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
                        <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
                        <a href="https://www.instagram.com/pharma_rose_egypt/" class="instagram"><i class="fa fa-instagram"></i></a>
                    </div>
                </div>
            </div>

            <div class="col-12 col-md-4 col-xl-3">
                <div class="single-footer-widget mb-80">

                    <h4 class="widget-title">Contact Us</h4>

                    <div class="contact-address">
                        <p>Address: Thailand </p>
                    </div>
                </div>
            </div>

        </div>
    </div>
</footer> -->




<!-- Footer Section Begin -->
<footer class="footer spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-3 col-md-6 col-sm-6">
                <div class="footer__about">
                    <div class="footer__about__logo">
                        <a href="{% url 'home' %}"><img src="{% static 'img/rose.png' %}" alt="" width="250" height="140"></a>
                    </div>
                    <ul>
                        <li>Address: Russian</li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-6 col-sm-6 offset-lg-1">
                <div class="footer__widget">
                    <h6>Useful Links</h6>
                    <ul>
                        <li><a href="{% url 'check:check_serial' %}">Check Products</a></li>
                        <li><a href="{% url 'about' %}">About Us</a></li>
                        <li><a href="{% url 'products:product_list' %}">About Our Shop</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-4 col-md-12">
                <div class="footer__widget">
                    <h6>Join Our Newsletter Now</h6>
                    <p>Get E-mail updates about our latest shop and special offers.</p>
                    <form action="#">
                        <input type="text" placeholder="Enter your mail">
                        <button type="submit" class="site-btn">Subscribe</button>
                    </form>
                    <div class="footer__widget__social">
                        <!-- <a target="_blank" href="https://www.facebook.com/Pharma_Rose-100403287998362/"><i class="fa fa-facebook"></i></a>
                        <a target="_blank" href="https://www.instagram.com/pharmaroseegypt/"><i class="fa fa-instagram"></i></a> -->
                    </div>
                </div>
            </div>
        </div>
        <div class="row">
            <div class="col-lg-12">
                <div class="footer__copyright">
                    <div class="footer__copyright__text"><p><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                    Copyright &copy;<script>document.write(new Date().getFullYear());</script> All rights reserved </p></div>
                    <!-- <div class="footer__copyright__payment"><img src="img/payment-item.png" alt=""></div> -->
                </div>
            </div>
        </div>
    </div>
</footer>
<!-- Footer Section End -->

templates/base/navbar.html
{% load static %}
    <!-- Header Area Start -->
    <header class="header-area">

        <!-- Main Header Start -->
        <div class="main-header-area">
            <div class="classy-nav-container breakpoint-off">
                <div class="container">
                    <!-- Classy Menu -->
                    <nav class="navbar navbar-expand-lg classy-navbar justify-content-between">

                        <!-- Logo -->
                        <a class="nav-brand" style="text-decoration:none;" href="{% url 'home' %}">
                          <img src="{% static 'img/rose.png' %}" width="50" height="50">
                          Ferrun Pharma</a>

                        <!-- Navbar Toggler -->
                        <div class="classy-navbar-toggler">
                            <span class="navbarToggler"></span>
                        </div>

                        <!-- Menu -->
                        <div class="classy-menu">
                            <!-- Nav Start -->
                            <div class="classynav">
                                <ul id="nav">
                                    <li>
                                      <a style='text-decoration:none;' href="{% url 'products:product_list' %}">Products</a>
                                    </li>
                                    <li><a style='text-decoration:none;' href="{% url 'about' %}">About us</a></li>
                                    <li><a style='text-decoration:none;' href="{% url 'contact:contact' %}">Contact us</a></li>
                                </ul>
                                <!-- Book Icon -->
                                <div class="book-now-btn ml-5 mt-4 mt-lg-0 ml-md-4">
                                    <a style="background: #ed790b;font-weight: bold;" href="{% url 'check:check_serial' %}" class="btn akame-btn">Check code</a>
                                </div>
                            </div>
                            <!-- Nav End -->
                        </div>
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- Header Area End -->

templates/base/navbar2.html
{% load static %}

<header class="header">
    <div class="container">
        <div class="row" style="margin-bottom: 50px;">
            <div class="col-lg-3">
                <div class="header__logo">
                    <a href="{% url 'home' %}">
                        <img src="{% static 'img/rose.png' %}" alt="Logo" style="width: 200px; height: 140px;">
                    </a>
                </div>
            </div>
            <div class="col-lg-8">
                <nav class="header__menu">
                    <ul>
                        <li class="active"><a href="{% url 'home' %}">Home</a></li>
                        <li><a href="{% url 'products:product_list' %}">Products</a></li>
                        <li><a href="{% url 'contact:contact' %}">Contact</a></li>
                        <li><a href="{% url 'about' %}">About Us</a></li>
                        <li><a href="{% url 'check:check_serial' %}">Check</a></li>
                    </ul>
                </nav>
                
                <form class="form-inline my-2 my-lg-0" action="{% url 'products:search_results' %}" method="GET"
                    value="{{request.GET.search}}">
                    <input class="form-control mr-sm-2" style="width: 500px;" name="search"
                        value="{{request.GET.search}}" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                </form>
            </div>
</header>

templates/home2.html
{% extends "base.html" %}
{% load static %}
{% block content %}


<!-- Hero Section Begin -->
<!-- <section class="hero">
        <div class="container">
            <div class="row">
                <div class="col-lg-3">
                    <div class="hero__categories">
                        <div class="hero__categories__all">
                            <i class="fa fa-bars"></i>
                            <span>All Categories</span>
                        </div>
                        <ul>
                        {% for category in all_categories %}
                            <li><a href="{% url 'products:category_product_list' category.slug %}">{{category.name}}</a></li>
                        {% empty %}
                        <div class="post-content text-center">
                            <p>No Categories Yet!</p>
                        </div>
                        {% endfor %}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
    </section> -->
<!-- Hero Section End -->


<!-- Search form -->

<!-- <div class="container">
    <div class="row">
        <div class="col-lg-9">
            <form action="{% url 'products:search_results' %}" method="GET" value="{{request.GET.search}}">
                <input name="search" value="{{request.GET.search}}" class="form-control" 
                    type="text" placeholder="Search.." aria-label="Search">
                <button type="submit" class="btn btn-primary" >Search</button>
              </form>
        </div>
    </div>
</div> -->


<div class="swiper-container">
    <div class="swiper-wrapper">
        <div class="swiper-slide"> <img width="500" height="600" src="{% static 'images/01.jpeg' %}"> </div>
        <div class="swiper-slide"> <img width="500" height="600" src="{% static 'images/03.jpeg' %}"> </div>
        <div class="swiper-slide"> <img width="500" height="600" src="{% static 'images/02.jpeg' %}"> </div>
    </div>
</div>



<!-- Categories Section Begin -->
<!-- <section class="categories">
        <div class="container">
            <div class="row">
                <div class="categories__slider owl-carousel">
                    <div class="col-lg-9">
                        <div class="categories__item set-bg" data-setbg="{% static 'images/2.jpg' %}">
                        </div>
                    </div>

                    <div class="col-lg-9">
                        <div class="categories__item set-bg" data-setbg="{% static 'images/3.jpg' %}">
                        </div>
                    </div>

                    <div class="col-lg-9">
                        <div class="categories__item set-bg" data-setbg="{% static 'images/4.jpg' %}">
                        </div>
                    </div>

                    <div class="col-lg-9">
                        <div class="categories__item set-bg" data-setbg="{% static 'images/5.jpg' %}">
                        </div>
                    </div>

                    <div class="col-lg-9">
                        <div class="categories__item set-bg" data-setbg="{% static 'images/6.jpg' %}">
                        </div>
                    </div>

                    <div class="col-lg-9">
                        <div class="categories__item set-bg" data-setbg="{% static 'images/7.jpg' %}">
                        </div>
                    </div>

                    <div class="col-lg-9">
                        <div class="categories__item set-bg" data-setbg="{% static 'images/8.jpg' %}">
                        </div>
                    </div>
                    <div class="col-lg-9">
                        <div class="categories__item set-bg" data-setbg="{% static 'images/11.jpg' %}">
                        </div>
                    </div>
                    <div class="col-lg-9">
                        <div class="categories__item set-bg" data-setbg="{% static 'images/12.jpg' %}">
                        </div>
                    </div>

                </div>
            </div>
        </div>
    </section> -->
<!-- Categories Section End -->

<!-- Featured Section Begin -->
<section class="featured spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title">
                    <h2>Categories</h2>
                </div>
            </div>
        </div>
        <div class="row featured__filter">
            {% for category in all_categories %}
            <div class="col-lg-2 col-md-2 col-sm-2">
                <div class="featured__item">
                    <div class="featured__item__text">
                        <h6><a href="{% url 'products:category_product_list' category.slug %}">{{category.name}}</a></h6>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section>


<!-- <section class="featured spad">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="section-title">
                    <h2>Featured Product</h2>
                </div>
            </div>
        </div>
        <div class="row featured__filter">
            {% for product in all_products %}

            <div class="col-lg-3 col-md-4 col-sm-6 mix oranges fresh-meat">
                <div class="featured__item">
                    <div class="featured__item__pic set-bg" data-setbg="{{product.image.url}}">
                    </div>
                    <div class="featured__item__text">
                        <h6><a href="{% url 'products:product_detail' product.slug %}">{{product.name}}</a></h6>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div>
    </div>
</section> -->
<!-- Featured Section End -->
{% endblock %}